version: '2'
services:
  accumulo_1:
    build: ./accumulo
    depends_on:
      - hadoop_master
      - zoo1
      - zoo2
      - zoo3
  accumulo_2:
    build: ./accumulo
    depends_on:
      - accumulo_1
  hadoop_master:
    build: ./hadoop
  hadoop_slave:
    build: ./hadoop

  zoo1:
    build: ./zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    build: ./zookeeper
    restart: always
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    build: ./zookeeper
    restart: always
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
